from build import ROOT,write
import json
# Each row gives two increasingly specific prompts; the third points to a concrete invariant.
hints={
'02-pretraining':[
('Separate byte values from special IDs.','Encode the string before adding sequence boundaries.','Empty text still has BOS and EOS.'),
('Identify the token each input position predicts.','The target window starts one position later.','A window needs context+1 available tokens.'),
('Work with logits rather than rounded probabilities.','Subtract the selected logit from a stable log normalizer.','Average over every target position and keep the result differentiable.'),
('Normalize magnitude without subtracting the mean.','Reduce squared values over the final dimension.','Epsilon belongs inside the square root; learned weights scale channels afterward.'),
('Inspect a single adjacent coordinate pair.','Position times frequency gives its rotation angle.','Position zero is identity and each pair preserves squared norm.'),
('Map a local query row to its absolute position.','Consecutive groups of query heads share one KV head.','Normalize scores over visible keys, never over query rows.'),
('Draw the two residual branches separately.','Attention projection and SwiGLU return to model width.','The feed-forward gate and up projection multiply before the down projection.'),
('Trace one sequence through embeddings and every layer.','Register modules under the exact checkpoint names.','Return raw logits and post-rotation keys; keep the dense graph differentiable.'),
('Separate moment updates from parameter decay.','Bias correction depends on the incremented step count.','Decoupled decay acts on parameters, not on the raw gradient.'),
('Check the three endpoints before the interior.','Warmup reaches peak exactly at its boundary.','Clamp the cosine fraction after the total step count.'),
('Treat all parameter gradients as one vector.','Compute one norm before changing any tensor.','Use one common scale factor; reject nonfinite norms before mutation.'),
('Count the actual target tokens.','Accumulate loss sums, not equally weighted sequence means.','Zero gradients once, backpropagate the aggregate once, then step.'),
('List what affects the next update besides weights.','Adam moments and CPU RNG state must be saved.','A resume checkpoint and an inference export have different consumers.'),
('Compare the next update, not just loaded values.','Restore optimizer hyperparameters as well as moments.','Restore RNG after constructing the replacement model.'),
('Try memorizing one short sequence as a diagnostic.','Keep initialization inside a local random-state scope.','Reuse train_step so the tested update is the one used by the loop.'),
('Record the architecture and tokenizer with the weights.','Detach, clone and move exported tensors to CPU.','Hash the finished file bytes; export no optimizer state.')],
'03-data':[
('Distinguish original content from its matching representation.','Unicode compatibility normalization precedes casefolding.','Whitespace collapse should be idempotent.'),
('Choose a stable cross-process content identity.','Hash the normalized UTF-8 bytes.','Python hash is not a persistent content ID.'),
('Count words and their most frequent occurrence.','The repetition denominator is total word count.','Both thresholds include equality; empty content still fails.'),
('Choose which duplicate record survives.','Track normalized content IDs while preserving input order.','Return new dictionaries so annotations do not modify the raw records.'),
('A shingle is a consecutive word window.','Enumerate only windows with all n words present.','Short documents produce no windows, not one empty window.'),
('Similarity edges are not themselves duplicate groups.','Take connected components over the pairwise matches.','A-B and B-C edges put A,B,C together even without an A-C edge.'),
('Assign one bucket to an entire group.','Choose group identity independently of input ordering.','The smallest member ID and salt determine the digest bucket.'),
('Check candidates against reserved content only.','Use both exact normalized matches and shingle overlap.','Short exact matches must still be removed when their shingle sets are empty.'),
('Separate the choice of source from the choice of record.','Sort source names before applying seeded randomness.','Zero weight removes a source from draws without changing the original data.'),
('Preserve three coordinate systems: document, packed row and document position.','Flush before adding a document that would overflow the current block.','Mask first-document targets and padding; do not split an oversized document silently.'),
('Visibility requires both causality and matching segment identity.','Padding has no valid segment.','A query cannot read another document even if that key is earlier.'),
('Choose serialization before computing the digest.','A newline follows each record, including the last.','Check existing outputs before writing either file.'),
('Order the policies before composing them.','Validate raw IDs, then filter, deduplicate, decontaminate and group.','Annotate copied records with split and content identity before writing.')],
'04-finetuning':[
('Create supervision information while serializing.','Role headers are context even for assistant messages.','Assistant content and its EOS are supervised; BOS and headers are not.'),
('Keep input visibility separate from target supervision.','Right-padding needs both a false attention bit and label -100.','Leave shifting to the loss function.'),
('Pair a target with the logit immediately before it.','Apply the mask after shifting the labels.','Divide by the number of supervised targets, not by padded sequence length.'),
('Write the matrix shapes before choosing their order.','One factor starts nonzero and the other starts at zero.','The low-rank path must preserve arbitrary leading input dimensions.'),
('Resolve all requested module names before replacing any.','Qualified paths distinguish identically named nested layers.','Validation failure must leave every target module unchanged.'),
('Identify adapter parameters by object membership.','Freeze the whole model, then select actual adapter A/B objects.','An unrelated parameter named A is not sufficient evidence of an adapter.'),
('Construct the optimizer from the intended trainable parameters.','Use the same masked loss tested in the prior stage.','The first update may move B without moving A.'),
('Compare the adapter path with an equivalent dense weight.','Preserve the original layer while constructing the merged result.','Include alpha/rank exactly once.'),
('Score only response targets under their preceding context.','Sum selected log probabilities separately for each example.','An all-masked row sums to zero; do not normalize by response length.'),
('Compute two chosen-versus-rejected margins.','Subtract the reference margin from the policy margin.','The reference contributes values but must not receive gradients.'),
('Keep policy and reference execution roles separate.','Reference evaluation runs without a differentiation graph.','When both models match, the initial loss is log(2).'),
('Save adapter state without including base weights.','Use qualified module paths and actual adapter types.','Detached CPU clones prevent later training from altering the snapshot.'),
('An adapter is meaningful relative to a particular base.','Store rank and scale alongside its matrices.','The digest returned describes adapter file bytes; base_sha256 names a different artifact.'),
('Plan the whole restore before modifying parameters.','Check identity, configuration, keys and every shape first.','A malformed final tensor must not cause partial restoration of earlier tensors.')],
'05-evaluation':[
('Decide exactly which differences the metric ignores.','ASCII punctuation removal differs from replacing punctuation with spaces.','Do not silently add article removal or semantic matching.'),
('Treat references as alternative valid answers.','Normalize prediction and references under the same policy.','An empty reference set is invalid data, not a score of zero.'),
('Map every continuation target to its preceding logit.','The prompt supplies context but its targets do not contribute.','The final model row predicts a token outside the observed sequence.'),
('Keep summed and normalized scoring as explicit alternatives.','Divide by continuation token count only in normalized mode.','A tie chooses the earliest candidate.'),
('Return to total NLL and token counts before aggregation.','Apply the exponential only after computing global mean NLL.','A mean of document perplexities changes both weighting and the nonlinear operation.'),
('Fix the meaning of each axis.','Increment one true-row/predicted-column entry per case.','Keep declared empty classes in the matrix.'),
('Compute class scores from row and column counts.','Each class denominator is true count plus predicted count.','Macro includes zero-score absent classes under this contract.'),
('Keep each example’s two model scores paired.','Resample indices, then apply them to score differences.','Identical models produce exactly zero in every resample.'),
('Treat IDs as join keys, not presentation order.','Validate complete matching sets before sorting.','Sorting determines a stable index order for the seeded bootstrap.'),
('Ask whether examples or groups receive equal weight.','Keep counts beside every group score.','The worst group can be invisible in a dominant-group micro average.'),
('Group observations by confidence before measuring gaps.','Weight each bin by its number of observations.','Confidence one belongs to the final bin, not an out-of-range index.'),
('Separate the first token from continuation tokens.','Decode elapsed time starts at the first token timestamp.','One token has no decode interval and therefore no decode throughput estimate.'),
('Expose only prompts to the prediction callback.','Preserve identities and every case in the denominator.','Propagate prediction failures rather than dropping difficult examples.'),
('Validate JSON serialization before opening the destination.','Reject nonfinite values and preserve Unicode.','Hash the exact canonical bytes including their trailing newline.')],
'07-distributed':[
('Assign every example to exactly one rank.','A strided sequence naturally gives unequal local counts.','Do not pad by duplicating examples.'),
('Use quotient and remainder to balance ownership.','Earlier ranks receive the remainder elements.','Half-open empty ranges still have valid start=end metadata.'),
('Fix one ordered flat layout for communication.','Concatenation can preserve gradients while owning new storage.','Validate dtype and device before flattening.'),
('Track a cursor through the flat buffer.','Each shape consumes its product of dimensions.','Return views; exact coverage is required.'),
('Compare with one large-batch objective.','Use total examples as the denominator across all microbatches.','Clear gradients once and do not update between microbatches.'),
('An average of averages needs weights.','Reduce weighted sums and counts in the same order on every rank.','Zero-work ranks still enter both collectives.'),
('All replicas must apply the same final gradient.','Sum local losses and gradients, then divide by global count.','An empty local batch must not return before collectives.'),
('A slice can still retain the full original storage.','Use the balanced contiguous bounds for ownership.','Clone only the owned momentum range.'),
('Separate replicated parameters from sharded optimizer state.','Update only the owned range, then gather the updated parameter pieces.','Pad collective payloads but trim each rank to its true ownership length.'),
('Check all gradients before dividing any.','A nonfinite value makes the entire local unscale fail.','Missing gradients can be ignored; invalid scale cannot.'),
('Distinguish activation recomputation from file checkpoints.','Use the non-reentrant checkpoint primitive.','A backward pass should trigger another function execution when intermediates are needed.'),
('Validate global coverage before assembling values.','Sort shards by range, then advance one coverage cursor.','Reject both gaps and overlaps, even when the final element count looks right.'),
('The skip decision must agree on every rank.','Reduce a finite flag with an all-ranks conjunction.','One rank’s infinity must make every rank return false before an update.'),
('CPU semantics do not establish CUDA execution.','Use one process and local device assignment per GPU.','NCCL payloads must be on the selected GPU and updates must match the global reference.')],
'08-releases':[
('Byte identity requires a serialization policy.','Sort keys and choose separators before hashing.','Reject nonfinite numbers and include the terminal newline.'),
('The digest should not depend on read chunk boundaries.','Update one hash state across bounded reads.','An empty file still has a well-defined digest.'),
('Check resolved containment rather than string prefixes.','Reject parent traversal before resolving symlinks.','The resolved target must be a regular file under the resolved root.'),
('Select the bundle boundary explicitly.','Sort paths and record both size and digest.','Copy metadata so caller mutations cannot rewrite the manifest.'),
('Byte size is necessary but not sufficient.','Validate every listed object’s digest as well as its path.','Equal-length corruption must fail.'),
('A content-addressed object must match its own name.','Copy to a temporary file and verify before publication.','An already present but corrupted object is an error, not a cache hit.'),
('Bind the report to both model and dataset.','Recompute its aggregate from unique per-case scores.','A correct digest does not excuse an inconsistent accuracy or count.'),
('Separate comparability checks from policy failures.','Apply evidence size, quality floor and regression limits in declared order.','An exactly satisfied threshold passes.'),
('Assignment must survive retries and process restarts.','Convert a stable salted digest into a unit interval bucket.','The same salt makes larger fractions extend the existing cohort.'),
('Keep failed requests in operational accounting.','Sort latencies before applying the stated percentile rule.','The nearest-rank index is based on all observations.'),
('Decide whether there is enough evidence before applying thresholds.','Either excessive errors or excessive latency can trigger rollback.','Threshold equality is a keep decision after the minimum count.'),
('Atomic visibility and concurrent decision safety are different.','Lock, reread, compare the expected version, then replace.','An idempotent promotion must not erase the earlier previous pointer.'),
('Rollback is another version-checked promotion.','Read the prior digest but preserve the expected-current check.','A concurrent change must reject the stale rollback.'),
('Bind evidence to actual model bytes before changing active state.','Run validation and the quality policy before registering artifacts.','Promotion still needs compare-and-swap even after every quality check passed.')]
}
for slug,rows in hints.items():
    course=ROOT/slug; path=course/'course/stages.json'; stages=json.loads(path.read_text())
    assert len(rows)==len(stages),(slug,len(rows),len(stages))
    for stage,clues in zip(stages,rows): stage['hints']=clues
    write(path,json.dumps(stages,indent=2))
